### ISSUE TITLE
Why local vagrant boxes?

### ISSUE THREAD

**Issue by salderma** [rgl/windows-domain-controller-vagrant#10]
Hi,

I notice rgl has vagrant cloud profile. Just curious why these Vagrantfiles aren't setup to use boxes from vagrant cloud.

**Comment by rgl** [comment]
Those vagrant cloud images are a stalled experiment of mine. Since I ended up not using them that much, I didn't invest more time on them. Hence, all my projects are using local built boxes.

**Comment by salderma** [comment]
Ok.
