### ISSUE TITLE
Functionality for Linux Host - SMB Shared Folders

### ISSUE THREAD

**Issue by salderma** [rgl/windows-domain-controller-vagrant#11]
Hi,
I'm curious... the README shows examples of using this project with either virtualbox or libvirt, yet the Vagrant Sync'd Folders are SMB based, which limits host OS's to Windows or Mac OSX.  I notice in the Packer projects for building your base boxes, that rsync is installed on the windows boxes.  Will rsync not work for this effort? 

I run Linux as my host platform and was really looking to build off your work to include adding Windows AD infrastructure into my Vagrant multi-system infrastructure models.

**Comment by rgl** [comment]
SMB sync folders also work in linux (e.g. ubuntu) after you apply the patch from https://github.com/hashicorp/vagrant/pull/9948

You can see that patch being applied to vagrant in one of:

1. https://github.com/rgl/xfce-desktop-vagrant/blob/1a6e14dfd25a955f2474f4b5c1cd2c69e16dbc04/provision-virtualization-tools.sh#L87-L98
2. https://github.com/rgl/infra-toolbox/blob/a6a9393be6ebbc4b9e5c9169f0a63103b99af513/playbooks/roles/vagrant/tasks/main.yml#L49-L71

Sometime I want to use a real share to share files between the guest and the host (like in this windows-domain-controller-vagrant repository, where the [guest copies the ExampleEnterpriseRootCA.der file to the host](https://github.com/rgl/windows-domain-controller-vagrant/blob/master/provision/ca.ps1#L32-L36)). For those cases rsync is not appropriate as it normally only copies files from the host to the guest.
