### ISSUE TITLE
provisioning scripts encounter TLS problems for Windows Server 2016

### ISSUE THREAD

**Issue by salderma** [rgl/windows-domain-controller-vagrant#12]
Hi, is there a easy hack I can add to the provision scripts that will enable getting around this TLSv1 issue in 2016?  Can't install chocolatey or do a number of other things in the provisioning.

Also, just curious, have you looked into making the provision scripts idempotent?  ... so that provisioning can be run over and over again, such that anything that has already succeeded won't be tried on subsequent provisions?

**Comment by rgl** [comment]
To enable TLS v1.2 in Windows PowerShell take a look at https://github.com/rgl/windows-vagrant/blob/615d7ae7eb137af247a9ab4003fa840cb88e6a94/example/ps.ps1#L16-L18

This vagrant environment was not really made to be idempotent; that would require a more complex set of scripts (and probably they should be driven/written in something like Ansible).
