### ISSUE TITLE
Please add guide for change default user,administrator,group

### ISSUE THREAD

**Issue by patsevanton** [rgl/windows-domain-controller-vagrant#2]
Thanks for Project :)
Please add guide for change default user,administrator,group
Big thanks

**Comment by rgl** [comment]
Use the Source, Luke ;-)

Have a look at:

https://github.com/rgl/windows-domain-controller-vagrant/blob/master/provision/domain-controller-configure.ps1#L27
https://github.com/rgl/windows-domain-controller-vagrant/blob/master/provision/domain-controller-configure.ps1#L58
